config/routes.rb
Rails.application.routes.draw do
  root 'school_districts#index'
  devise_for :users,
             :controllers => { registrations: "my_devise/registrations"}

  resources :school_districts do
    resources :schools, only: [:new, :create, :index, :show, :edit, :update]
    resources :school_faculty_memberships, only: [:index, :new, :create]
  end

  resources :schools, only: :show do
    resources :school_departments, only: [:new, :create]
  end

  resources :school_district_invites
end

app/models/school_district.rb
class SchoolDistrict < ActiveRecord::Base
  belongs_to :user
  has_many :schools
  has_many :school_district_memberships
  has_many :school_district_invites

  validates :user,
    presence: true

  validates :name,
    presence: true

  validates_format_of :website, :with => URI::regexp(%w(http https))

  validates :address,
    presence: true

  validates :city,
    presence: true

  validates :state,
    presence: true

  validates :zip_code,
    presence: true

  validates_format_of :zip_code,
                      :with => %r{\d{5}(-\d{4})?},
                      :message => "should be 12345 or 12345-1234"

  validates :user_id,
    presence: true,
    numericality: { only_integer: true }

  def self.search(query)
    where("name ILIKE?", "%#{query}%")
  end

  def district_admin
    user
  end
end

app/controllers/school_districts_controller.rb
class SchoolDistrictsController < ApplicationController
  def index
    if params[:query]
      @school_districts = SchoolDistrict.search(params[:query])
    end
  end

  def show
    @school_district = SchoolDistrict.find(params[:id])
    @invite = SchoolDistrictInvite.new
  end

  def new
    @school_district = SchoolDistrict.new
  end

  def create
    @school_district = SchoolDistrict.new(school_district_params)
    @school_district.user = current_user
    if @school_district.save
      flash[:notice] = 'Successfully created new school district.'
      redirect_to school_district_path(@school_district)
    else
      flash[:alert] = 'Unable to save.'
      render :new
    end
  end

  def edit
    @school_district = SchoolDistrict.find(params[:id])
  end

  def update
    school_district = SchoolDistrict.find(params[:id])
    if school_district.update_attributes(school_district_params)
      flash[:notice] = 'You have successfully edited your school district.'
      redirect_to school_district_path(school_district)
    else
      flash[:alert] = 'Unable to save.'
      render :edit
    end
  end

  private

  def school_district_params
    params.require(:school_district).permit(:name, :website, :address, :city,
      :state, :zip_code, :user_id)
  end
end

app/helpers/school_districts_helper.rb
module SchoolDistrictsHelper
  def states_array
    %w(AK AL AR AZ CA CO CT DC DE FL GA HI IA ID IL IN KS KY LA
    MA MD ME MI MN MO MS MT NC ND NE NH NJ NM NV NY OH OK OR PA RI SC SD TN TX UT VA VT WA WI WV WY)
  end

  def account_type_options
    %w(Administrator Teacher)
  end
end

app/views/school_districts/_edit_form.html.erb
<%= form_for @school_district do |f| %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name, auto_focus: true %>
  </div>

  <div class="field">
    <%= f.label :website %><br/>
    <%= f.text_field :website %>
  </div>

  <div class="field">
    <%= f.label :address %><br/>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :city %><br/>
    <%= f.text_field :city %>
  </div>

  <div class="state_field">
    <%= f.label :state %><br/>
    <%= f.select :state, options_for_select(states_array) %>
  </div>

  <div class="field">
    <%= f.label :zip_code, 'Zip Code' %><br/>
    <%= f.text_field :zip_code %>
  </div>

  <%= f.submit 'Submit' %>

<% end %>

app/views/school_districts/_form.html.erb
<%= form_for @school_district do |f| %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name, auto_focus: true %>
  </div>

  <div class="field">
    <%= f.label :website %><br/>
    <%= f.text_field :website %>
  </div>

  <div class="field">
    <%= f.label :address %><br/>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :city %><br/>
    <%= f.text_field :city %>
  </div>

  <div class="state_field">
    <%= f.label :state %><br/>
    <%= f.select :state, options_for_select(@states_array) %>
  </div>

  <div class="field">
    <%= f.label :zip_code, 'Zip Code' %><br/>
    <%= f.text_field :zip_code %>
  </div>

  <%= f.submit 'Create School District' %>

<% end %>

app/views/school_districts/_new_form.html.erb
<%= form_for @school_district do |f| %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name, auto_focus: true %>
  </div>

  <div class="field">
    <%= f.label :website %><br/>
    <%= f.text_field :website %>
  </div>

  <div class="field">
    <%= f.label :address %><br/>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :city %><br/>
    <%= f.text_field :city %>
  </div>

  <div class="state_field">
    <%= f.label :state %><br/>
    <%= f.select :state, options_for_select(states_array) %>
  </div>

  <div class="field">
    <%= f.label :zip_code, 'Zip Code' %><br/>
    <%= f.text_field :zip_code %>
  </div>

  <%= f.submit 'Create School District' %>

<% end %>

app/views/school_districts/_search_form.html.erb
<%= form_tag school_districts_path, method: :get, id: "s-tag" do %>
  <%= text_field_tag :query %>
  <%= submit_tag "Search", id: "search-button" %>
<% end %>

app/views/school_districts/_search_results.html.erb
<% @school_districts.each do |school_district| %>
  <li><%= link_to "#{school_district.name}", school_district_path(school_district) %>
<% end %>

app/views/school_districts/edit.html.erb
<h3>Fill out the form below.</h3>

<%= render "edit_form" %>

app/views/school_districts/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

<div id="search-field">
  <%= render "search_form" %>
</div>

<% if @school_districts %>
  <div id="search-results">
    <%= render "search_results" %>
  </div>
<% end %>

app/views/school_districts/new.html.erb
<h3>Fill out the form below.</h3>

<%= render "form" %>

app/views/school_districts/show.html.erb
<h2><%= @school_district.name %></h2>

<% if current_user == @school_district.district_admin %>
  <p class="edit"><%= link_to "Edit District Information", edit_school_district_path(@school_district) %></p>
<% end %>
<p class="district-admin">District Administrator: <%= @school_district.user.name %></p>

<div class="address-box">
  <p><%= @school_district.address %></p>
  <p><%= "#{@school_district.city}, #{@school_district.state} #{@school_district.zip_code}" %></p>
</div>

<div class="schools-box">
  <%= link_to "Add School", new_school_district_school_path(@school_district, @school) %>
</div>

<% if current_user == @school_district.district_admin %>
  <div>
    <%= link_to "Staffing Assignments", school_district_school_faculty_memberships_path(@school_district, @district_memberships) %>
  </div>
<% end %>

<% if current_user == @school_district.district_admin %>
  <div class="sd-membership-invite-box">
    <%= form_for @invite, url: school_district_invites_path do |f| %>
      <%= f.hidden_field :school_district_id, value: @school_district.id %>
      <%= f.label :email, "Enter an email address to invite users to this district." %>
      <%= f.email_field :email %>
      <%= f.label :account_type, "What type of account will this invitee have:" %>
      <%= f.select :account_type, options_for_select(account_type_options), { include_blank: '' } %>
      <%= f.submit 'Send Invitation' %>
    <% end %>
  </div>
<% end %>