config/routes.rb
Rails.application.routes.draw do
  root 'school_districts#index'
  devise_for :users,
             :controllers => { registrations: "my_devise/registrations"}

  resources :school_districts do
    resources :schools, only: [:new, :create, :index, :show, :edit, :update]
    resources :school_faculty_memberships, only: [:index, :new, :create]
  end

  resources :schools, only: :show do
    resources :school_departments, only: [:new, :create]
  end

  resources :school_district_invites
end

app/models/school_faculty_membership.rb
class SchoolFacultyMembership < ActiveRecord::Base
  belongs_to :school_district_membership
  belongs_to :school

  validates :school_id,
    presence: true,
    numericality: { only_integer: true }

  validates :school_district_membership_id,
    presence: true,
    numericality: { only_integer: true }

  def user
    school_district_membership.user
  end

  def user_name
    school_district_membership.user.name
  end
end

app/controllers/school_faculty_memberships_controller.rb
class SchoolFacultyMembershipsController < ApplicationController
  def index
    @school_district = SchoolDistrict.find(params[:school_district_id])
    @schools = @school_district.schools.order(name: :asc)
  end

  def new
    @school_district = SchoolDistrict.find(params[:school_district_id])
    @schools = School.where(
      school_district_id: @school_district.id).map { |school| school.name }
    @district_members = SchoolDistrictMembership.where(
      school_district_id: @school_district.id)
    @faculty_memberships = SchoolFacultyMembership.new
  end

  def create
    @school_district = SchoolDistrict.find(params[:school_district_id])
    @schools = School.where(
      school_district_id: @school_district.id)
    @school_names = @schools.map { |school| school.name }
    @district_members = SchoolDistrictMembership.where(
      school_district_id: @school_district.id)

    @schools.each do |school|
      @district_members.each do |district_member|
        if params[district_member.user.name] == school.name
          membership = SchoolFacultyMembership.find_or_initialize_by(
            school_district_membership_id: district_member.id)
          membership.school_id = @schools[@school_names.index(
            params[district_member.user.name])].id
          membership.save
        end
      end
    end
    flash[:notice] = "School faculty assignments are saved."
    redirect_to school_district_school_faculty_memberships_path(@school_district)
  end
end

app/views/school_faculty_memberships/index.html.erb
<%= link_to "Edit Staffing Assignments", new_school_district_school_faculty_membership_path(@school_district, @faculty_memberships) %>

<% @schools.each do |school| %>
  <%= link_to school.name, school_district_school_path(@school_district, school) %>
  <ul>
    <% school.school_faculty_memberships.each do |member| %>
      <li><%= member.user_name %></li>
    <% end %>
  </ul>
<% end %>

app/views/school_faculty_memberships/new.html.erb
<h3>Use the form below to assign district faculty to their respective</h3>

<%= form_for ([@school_district, @faculty_memberships]) do |f| %>
  <ul>
    <% @district_members.each do |district_member| %>
      <li>
        <%= label_tag "#{district_member.user.name}" %>
        <%= select_tag(:school_id, options_for_select(@schools),
        name: district_member.user.name, include_blank: true) %>
      </li>
    <% end %>
  </ul>
  <%= f.submit "Save School Assignments" %>
<% end %>