config/routes.rb
Rails.application.routes.draw do
  root 'school_districts#index'
  devise_for :users,
             :controllers => { registrations: "my_devise/registrations"}

  resources :school_districts do
    resources :schools, only: [:new, :create, :index, :show, :edit, :update]
    resources :school_faculty_memberships, only: [:index, :new, :create]
  end

  resources :schools, only: :show do
    resources :school_departments, only: [:new, :create]
  end

  resources :school_district_invites
end

app/models/school.rb
class School < ActiveRecord::Base
  belongs_to :school_district
  has_many :school_faculty_memberships
  has_many :school_departments

  validates :name,
    presence: true

  validates_format_of :website, :with => URI::regexp(%w(http https))

  validates :address,
    presence: true

  validates :city,
    presence: true

  validates :state,
    presence: true

  validates :zip_code,
    presence: true

  validates_format_of :zip_code,
                      :with => %r{\d{5}(-\d{4})?},
                      :message => "should be 12345 or 12345-1234"

  validates :school_district_id,
    presence: true,
    numericality: { only_integer: true }

  validates :status,
    presence: true,
    inclusion: { in: %w(Active Inactive) }
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def show
    @school = School.find(params[:id])
  end

  def new
    @school_district = SchoolDistrict.find_by(id: params[:school_district_id])
    @school = School.new
  end

  def create
    @school = School.new(school_params)
    @school_district = SchoolDistrict.find_by(id: params[:school_district_id])
    @school.school_district_id = @school_district.id

    if @school.save
      flash[:notice] = "You have successfully added a school to your district."
      redirect_to school_district_school_path(@school_district, @school)
    else
      flash[:alert] = "Fill out the forms correctly."
      render :new
    end
  end

  def edit
    @school_district = SchoolDistrict.find_by(id: params[:school_district_id])
    @school = School.find(params[:id])
  end

  def update
    @school_district = SchoolDistrict.find_by(id: params[:school_district_id])
    @school = School.find(params[:id])

    if @school.update_attributes(school_params)
      flash[:notice] = "You have successfully updated this school."
      redirect_to school_district_school_path(@school_district, @school)
    else
      flash[:alert] = "Fill out the forms correctly."
      render :edit
    end
  end

  private

  def school_params
    params.require(:school).permit(:name, :website, :address, :city, :state,
      :zip_code, :school_type, :status)
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper

  def states_array
    %w(AK AL AR AZ CA CO CT DC DE FL GA HI IA ID IL IN KS KY LA
    MA MD ME MI MN MO MS MT NC ND NE NH NJ NM NV NY OH OK OR PA RI SC SD TN TX UT VA VT WA WI WV WY)
  end

  def school_types_array
    %w("high school" "middle school" "elementary school" "other")
  end

  def school_statuses
    %w(Active Inactive)
  end
end

app/views/schools/_edit_form.html.erb
<%= form_for [@school_district, @school] do |f| %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name, auto_focus: true %>
  </div>

  <div class="school_type_field">
    <%= f.label :school_type %><br/>
    <%= f.select :school_type, options_for_select(school_types_array) %>
  </div>

  <div class="field">
    <%= f.label :website %><br/>
    <%= f.text_field :website %>
  </div>

  <div class="field">
    <%= f.label :address %><br/>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :city %><br/>
    <%= f.text_field :city %>
  </div>

  <div class="state_field">
    <%= f.label :state %><br/>
    <%= f.select :state, options_for_select(states_array) %>
  </div>

  <div class="field">
    <%= f.label :zip_code, 'Zip Code' %><br/>
    <%= f.text_field :zip_code %>
  </div>
  
  <div class="status_field">
    <%= f.label :status %><br/>
    <%= f.select :status, options_for_select(school_statuses) %>
  </div>

  <%= f.submit 'Update School' %>
<% end %>

app/views/schools/_new_form.html.erb
<%= form_for [@school_district, @school] do |f| %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name, auto_focus: true %>
  </div>

  <div class="school_type_field">
    <%= f.label :type %><br/>
    <%= f.select :type, options_for_select(school_types_array) %>
  </div>

  <div class="field">
    <%= f.label :website %><br/>
    <%= f.text_field :website %>
  </div>

  <div class="field">
    <%= f.label :address %><br/>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :city %><br/>
    <%= f.text_field :city %>
  </div>

  <div class="state_field">
    <%= f.label :state %><br/>
    <%= f.select :state, options_for_select(states_array) %>
  </div>

  <div class="field">
    <%= f.label :zip_code, 'Zip Code' %><br/>
    <%= f.text_field :zip_code %>
  </div>

  <%= f.submit 'Create School' %>
<% end %>

app/views/schools/edit.html.erb
<% if @school.errors.any? %>
  <% @school.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
<% end %>

<h3><%= "Update #{@school.name}'s information below."%></h3>

<%= render "edit_form" %>

app/views/schools/new.html.erb
<% if @school.errors.any? %>
  <% @school.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
<% end %>

<h3>Fill out the form below to add a school to your district.</h3>

<%= render "new_form" %>

app/views/schools/show.html.erb
<h3><%= @school.name %></h3>
<li><%= "Status: #{@school.status}" %></li>
<li><%= link_to "Edit School Info", edit_school_district_school_path(@school.school_district, @school) %></li>
<li><%= link_to "Edit School Departments", new_school_school_department_path(@school, @school_department) %></li>

<p><%= link_to "#{@school.website}", @school.website %></p>
<p>School District: <%= @school.school_district.name %></p>
<p>District Administrator: <%= @school.school_district.user.name %></p>

<p>
  <%= @school.address %><br>
  <%= "#{@school.city}, #{@school.state} #{@school.zip_code}" %>
</p>