config/routes.rb
Rails.application.routes.draw do
  root 'school_districts#index'
  devise_for :users,
             :controllers => { registrations: "my_devise/registrations"}

  resources :school_districts do
    resources :schools, only: [:new, :create, :index, :show, :edit, :update]
    resources :school_faculty_memberships, only: [:index, :new, :create]
  end

  resources :schools, only: :show do
    resources :school_departments, only: [:new, :create]
  end

  resources :school_district_invites
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tracker.ly</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Trackerly</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'New School District', new_school_district_path %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>